#!/usr/bin/env python3
"""Generate TinyTang's original 4x4 terminal font and a native-size specimen."""
# SPDX-License-Identifier: MIT
from pathlib import Path

# Four hexadecimal rows, most significant bit at the left. Lowercase uses
# shorter forms where four rows permit them; this is a tiny display font,
# not a reduction of the desktop's 8x8 glyphs. DEL is the fallback box.
GLYPHS = {
    ' ': '0000', '!': '4404', '"': 'aa00', '#': 'afaf', '$': '6c36',
    '%': '9249', '&': '6cad', "'": '4400', '(': '2442', ')': '4224',
    '*': '0a4a', '+': '04e4', ',': '0048', '-': '00e0', '.': '0004',
    '/': '1248', '0': '6bd6', '1': '464e', '2': 'e168', '3': 'e262',
    '4': 'aaf2', '5': 'ec2c', '6': '68e6', '7': 'f124', '8': '6a6a',
    '9': '6ae2', ':': '0404', ';': '0408', '<': '2484', '=': '0e0e',
    '>': '8424', '?': 'e204', '@': '6bd6',
    'A': '69f9', 'B': 'eaea', 'C': '7887', 'D': 'e99e', 'E': 'f8cf',
    'F': 'f8c8', 'G': '78b7', 'H': '9f99', 'I': 'e44e', 'J': '322c',
    'K': '9aca', 'L': '888f', 'M': '9ff9', 'N': '9db9', 'O': '6996',
    'P': 'eae8', 'Q': '6997', 'R': 'eaca', 'S': '7c3e', 'T': 'f444',
    'U': '9996', 'V': 'aaa4', 'W': '999f', 'X': '9669', 'Y': '9644',
    'Z': 'f24f', '[': '6446', '\\': '8421', ']': '6226', '^': '4a00',
    '_': '000f', '`': '4200',
    'a': '06be', 'b': '8caa', 'c': '0787', 'd': '26aa', 'e': '06f7',
    'f': '64e4', 'g': '06e2', 'h': '8eaa', 'i': '4044', 'j': '202c',
    'k': '8acb', 'l': '4442', 'm': '0ffe', 'n': '0eaa', 'o': '0696',
    'p': '0ea8', 'q': '06a2', 'r': '06c8', 's': '07c3', 't': '4e46',
    'u': '0aa6', 'v': '0aa4', 'w': '0aaf', 'x': '0a4a', 'y': '0aa2',
    'z': '0e4e', '{': '64c6', '|': '4444', '}': 'c46c', '~': '05a0',
    chr(127): 'f99f',
}


def main():
    root = Path(__file__).resolve().parent.parent
    assert set(GLYPHS) == {chr(c) for c in range(32, 128)}
    lines = ['// SPDX-License-Identifier: GPL-3.0-only',
             '// Generated by tools/make_oled_font.py; original TinyTang glyphs.',
             'function automatic [15:0] oled_glyph(input [7:0] ch);',
             '    case (ch)']
    for ch, rows in sorted(GLYPHS.items()):
        assert len(rows) == 4
        lines.append(f"        8'h{ord(ch):02x}: oled_glyph = 16'h{rows};")
    lines += ["        default: oled_glyph = 16'hf99f;", '    endcase', 'endfunction']
    (root / 'fpga/desktop/oled_font.vh').write_text('\n'.join(lines) + '\n')
    # Native 96x64 proof sheet, also used by the deterministic panel probe.
    specimen = ['OLED TERMINAL 24X16     ', 'ABCDEFGHIJKLMNOPQRSTUVWX',
                'YZ 0123456789 +-*/=      ', 'abcdefghijklmnopqrstuvwx',
                'yz !?.,:;()[]{}<>_       ', 'root@tinytang:~# ls      ',
                'echo hello OLED         ', 'The quick brown fox     ',
                'jumps over 0123456789    ', 'WHITE RED GREEN BLUE    ',
                'input edit wrap scroll  ', 'unsupported: ' + chr(127),
                '123456789012345678901234', 'abcdefghijklmnopqrstuvwx',
                'ABCDEFGHIJKLMNOPQRSTUVWX', '4x4 font readability    ']
    data = bytearray()
    for y in range(64):
        row = specimen[y // 4].ljust(24)
        for x in range(96):
            bits = int(GLYPHS[row[x // 4]], 16)
            data.append(255 if bits & (1 << (15 - (y % 4)*4 - x % 4)) else 0)
    out = root / 'build/oled-terminal'
    out.mkdir(parents=True, exist_ok=True)
    (out / 'font-specimen.pgm').write_bytes(b'P5\n96 64\n255\n' + data)
    (out / 'font-specimen.txt').write_text('\n'.join(s.ljust(24) for s in specimen) + '\n')
    print('Generated oled_font.vh and native 96x64 font specimen')


if __name__ == '__main__':
    main()
