# Write the firmware's build identity into a header, on every build.
#
#   cmake -DSRC=<repository root> -DOUT=<header path> -P tinytang_build_id.cmake
#
# The identity is the commit the tree was built from, and, when the tree has
# changes that are not committed, a short hash of those changes:
#
#     318b23c                  built from a clean checkout of 318b23c
#     318b23c-dirty.4f1a9c2    built from 318b23c plus uncommitted changes
#
# The second form is the usual one here, because a cycle builds and deploys
# before it commits.  A bare "-dirty" would make two different test builds in
# one cycle look the same; hashing the diff tells them apart, and the same diff
# always gives the same identity.  Untracked files do not count, as they do not
# for git itself.
#
# This runs as a step of every build rather than once at configure time, which
# is the point: a value fixed at configure time goes stale exactly the way the
# image's __DATE__ string does.  The header is rewritten only when the identity
# changes, so an unchanged tree does not recompile anything.

execute_process(
    COMMAND git -C "${SRC}" rev-parse --short=7 HEAD
    OUTPUT_VARIABLE rev
    RESULT_VARIABLE rc
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET)

if(NOT rc EQUAL 0 OR rev STREQUAL "")
    set(id "unknown")
else()
    set(id "${rev}")
    execute_process(
        COMMAND git -C "${SRC}" diff HEAD --no-ext-diff --no-color
        OUTPUT_VARIABLE diff
        ERROR_QUIET)
    if(NOT diff STREQUAL "")
        string(SHA1 h "${diff}")
        string(SUBSTRING "${h}" 0 7 h)
        set(id "${rev}-dirty.${h}")
    endif()
endif()

set(content "/* Generated by cmake/tinytang_build_id.cmake on every build; do not edit. */\n#define TINYTANG_BUILD_ID \"${id}\"\n")

set(old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" old)
endif()
if(NOT old STREQUAL content)
    file(WRITE "${OUT}" "${content}")
endif()
